version: "3"
services:
  redis:
    image: redis

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  vote:
    image: voting-app
    ports:
      - 5000:80

  worker:
    image: woker-app

  result:
    image: result-app
    ports:
      - 5001:80

#version 1
#
#
#redis:
#  image: redis
#
#db:
#  image: postgres:9.4
#  environment:
#    POSTGRES_HOST_AUTH_METHOD: trust
#
#vote:
#  image: voting-app
#  ports:
#    - 5000:80
#  links:
#    - redis
#
#worker:
#  image: woker-app
#  links:
#    - db
#    - redis
#
#result:
#  image: result-app
#  ports:
#    - 5001:80
#  links:
#    - db